### ISSUE TITLE
Getting too many values to unpack warning

### ISSUE THREAD

**Issue by palash25** [comtihon/catcher#12]
This is my yaml

```
steps:
# Status endpoint
- http: {get: {url: 'http://localhost:5000/api/v2/status'}}

# Cluster health endpoint
- http: {get: {url: 'http://localhost:5000/api/v2/clusterHealth'}}

# indexAndType endpoint
- http:
  post:
      url: 'http://localhost:5000/api/v2/indexAndType'
      body: {email: 'someemail@email.com'}
```

I checked the yaml and it is valid and I was following the format from the docs but I still get this error `WARNING:catcher:Test catcher_test.yml failed: too many values to unpack (expected 1)` on the last step and it doesn't run because of it

**Comment by comtihon** [comment]
`post` should be inside `http` step.
Not on the same level.
F.e.
```
- http:
      post:
          url: 'http://localhost:5000/api/v2/indexAndType'
          body: {email: 'someemail@email.com'}
```
