### ISSUE TITLE
http module basic auth feature

### ISSUE THREAD

**Issue by anandsunderraman** [comtihon/catcher#21]
Does http module support basic auth feature.

I was looking for a way to do basic authentication with REST api.
I am not able to see a way to do it in docs. 
The other option would be to write an external step that creates the Base64 encoding and then use that in the http step for the headers

**Comment by comtihon** [comment]
Yeah, there is no basic auth option externalized, but you can do it by passing a custom Authorization header with `Basic <base64>`
You can try to use Jinja2 base64 encoding:
```
http: 
    post: 
         url: 'http://test.com'
         body: {'id': '{{ id }}', 'action': 'fee'}
         headers: {Authorization: 'Basic {{ username + ':' + password | b64encode }}'}
```
