### ISSUE TITLE
Concurrent test execution

### ISSUE THREAD

**Issue by comtihon** [comtihon/catcher#23]
In test conf object add concurrency group:
```
variables:
    foo: bar
config:
   concurrency:
         enabled: true
         group: teamA
steps:
....
```
If config.concurrency.enabled is true - test can be run concurrent.
If config.concurrency.group is true - no tests of the same group can be run at once.
Should use multiprocessing and create pool with CPU + 1
Test results in json/html should be concurrent safe.
