### ISSUE TITLE
skip/when condition

### ISSUE THREAD

**Issue by comtihon** [comtihon/catcher#31]
Add ability to skip step based on a logical condition like in [Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#the-when-statement)
F.e.:
```
steps:
  - docker: 
          start: 
            image: 'jamesdbloom/mockserver'
            ports:
              '1080/tcp': 8000
          when: 
            equals: {the: '{{ my_http_service_url }}', is: 'localhost'}
```
