### ISSUE TITLE
Skip_if not working in loop

### ISSUE THREAD

**Issue by beatstream69** [comtihon/catcher#354]
Using catcher-1.36.2

Let's try simple test:

```
variables:
  test_data: [ "NOT_PRESENT", "NOT_PRESENT", "PRESENT" ]
steps:
  - echo:
      name: 'echo test items'
      from: 'Items are {{ test_data }}'
  - loop:
      foreach:
        in: test_data
        do:
          - echo:
              name: 'echo test item'
              from: 'Item is {{ ITEM }}'
              register: {found: '{{ ITEM == "PRESENT" }}'}
          - echo:
              name: 'echo flag'
              from: 'Found flag is {{ found }}'
          - check:
              name: 'truefalse test'
              skip_if: '{{ not found }}'
              equals: {the: '{{ found }}', is: True}
```

"check" step must NOT fail test in any case
Also, first step in loop prints there some garbage: `INFO:catcher:Item is t`

**Comment by comtihon** [comment]
Probably it was not implemented, let me take a quick look, maybe it is a 5 min thing.
>  Also, first step in loop prints there some garbage: INFO:catcher:Item is t
this is because you iterate over a string "test_data", where "t" is the first element. To iterate over a variable use this:
```
loop:
      foreach:
        in: '{{ test_data }}'
        do:
          - echo:
              name: 'echo test item'
              from: 'Item is {{ ITEM }}'
              register: {found: '{{ ITEM == "PRESENT" }}'}

```
