### ISSUE TITLE
Is there support for Elasticsearch?

### ISSUE THREAD

**Issue by palash25** [comtihon/catcher#7]
Just like there is support for kafka and postgres, I was wondering if there is support for ES because we use those heavily in our microservices and were wondering if that would be possible, because writing ES request bodies with queries and aggreagations if writing them as a simple http request in catcher can be very cumbersome so it would be nice to have something like

```
elasticsearch:
    search:
        index: indexName
        query:
            bool: {{filter_query_body}}
```

I could try sending a PR for this if you don't have the time to implement this. Also I took a look at the codebase but I can't understand how the actions for kafka and postgres are implemented.
cc @comtihon

**Comment by comtihon** [comment]
Hi,
Unfortunately there is no ES support right now, but I think I can add it this weekend.
There is a [readme](https://catcher-test-tool.readthedocs.io/en/latest/source/modules.html) describing writing custom modules in python or other languages (there is a bash example).

**Comment by palash25** [comment]
Thanks for that, I will take a look at the README. If you cannot find the time to do the ES module during the weekend let me know and I will take a crack at this.

**Comment by comtihon** [comment]
Please update your catcher-modules and check whether it is what you need.
Feel free to close this issue ;)

**Comment by palash25** [comment]
Hi @comtihon thanks for adding ES support. I was trying it out but it didn't work. I installed catcher using pip `sudo pip3 install catcher_modules`

This was my yml file

```
steps:
- http: {get: {url: 'http://httpbin.org'}}
- elastic:
            search:
                url: 'http://127.0.0.1:9200'
                index: response_v2_862875ee3a88a6d09c95bdbda029ce2b
                _source: ['name']
            register: {docs: '{{ OUTPUT }}'}
```

When I ran this I got 

```
/usr/local/lib/python3.6/dist-packages/catcher/utils/file_utils.py:76: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(stream)
INFO:catcher:Step http OK
INFO:catcher:Step elastic failed: No module named 'elasticsearch'
WARNING:catcher:Test catcher_test.yml failed: No module named 'elasticsearch'

```

Then I installed the modules again by cloning the repo and installing the modules using `setup.py`

But it still didn't work

This is the output of my `pip freeze`

```
catcher==1.19.0
catcher-modules==3.1.0
```

I am a little out of touch with python so maybe I am missing something, but I can't really figure out why is this happening.
