### ISSUE TITLE
Any plans for supporting gRPC?

### ISSUE THREAD

**Issue by varunvora** [comtihon/catcher#97]

**Comment by comtihon** [comment]
can you please provide what you expect from catcher in terms of gRPC?
if it should be a separate step - what should it do?
Based on your expectations I can say whether it is possible and when it can be done.

**Comment by varunvora** [comment]
Just like catcher is making REST calls with the `http` step, I would prefer if it could make gRPC calls the same way. The request body would translate to a protobuf request and be able to parse the response to a JSON. 

From what I understand this would involve in introducing a new step and logic for building gRPC client, transcoding protobuf messages to JSON.

**Comment by comtihon** [comment]
I'll do it in a week.
I guess it should look like:
```
- grpc:
    request:
        schema: my_schema.proto
        data: '{{ my_data }}'
```

**Comment by varunvora** [comment]
If the server has reflection enabled, we need not specify a schema. That way the tests need not have the `.proto` file

**Comment by comtihon** [comment]
please check the PR opened https://github.com/comtihon/catcher/pull/98
I've added a possibility to make grpc calls. Although, I haven't figured out how to use reflection (last time I used protobuffs ~10 years ago) and I made schema support.
So now it looks like:
```
- grpc:
          call:
                url: 'localhost:50051'
                function: greeter.greet
                schema: 'greeter.proto'
                data: '{{ data }}'
          register: {value: '{{ OUTPUT.name }}'}
```
I've covered it with tests based on helloworld examples. Don't know if it will work with streaming.
Please provide more examples (ideally a docker image or server's source code which I can use to test the implementation) if you need something advanced.
